on:
  push:
    branches: [master]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: psacawa/netshoot:latest
